const Strings  =({
    appName:'TokTown',
    start_a_meeting:'Start a Meeting',
    start_a_meeting_desc:'Start or join a video meeting on the go',
    join_meeting:'Join The\nMeeting',
    settings:'Settings',
    meetings:'Meetings',
    general:'General',
    version:'Version',
    tellOther:'Tell Others About Toktown',
    rateTokTown:'Rate Toktown in the App Store',
    privacyPolicy:'Privacy Policy',
    termsOfService:'Terms Of Service',
    communityStandards:'Community Standards',
    copyright:'Copyright © TokTown.com',
    company_name:'Company Name',
    meeting_name:'Meeting Name',
    company_name_subtext: 'srcligix',
    meeting_name_subtext: 'testing',
    your_name: 'Your Name',
    your_email: 'Your Email',
    host_pin: 'Host Pin',
    permission: 'Permission',
    meetandchat:'Meet & Chat',
    contacts:'Contacts',
    newMeetings:'New Meetings',
    chat:'Chat',
    info:'Info',
    polling:'Polling',
    record:'Record',
    shareScreen:'ShareScreen',

});

export default Strings;